#!/bin/bash
RED='\033[0;31m'
Yellow='\033[0;33m'
Cyan='\033[0;36m'
NC='\033[0m' # No Color

function fs ()
{
printf "${Yellow} ===== FS ====${NC}\n\n"
df -PTh | grep -v tmpfs;echo
printf "${Yellow} ===== FS Permission ==== ${NC}\n\n"
df -PTh | egrep -v 'tmpfs|Filesystem' | awk '{print $NF}' | while read line;do ls -ld $line;done | column -t
printf "${Yellow}=== pvs output===${NC}\n\n"
pvs
printf "${Yellow}=== vgs output===${NC}\n\n"
vgs
printf "${Yellow}=== lvs output===${NC}\n\n"
lvs
}

function network ()
{
printf "${Yellow} ===== routes and ips ====${NC}\n\n"
ip r;echo
printf "${Yellow} ===== Interfaces ====${NC}\n\n"
ip a | grep mtu | column -t
}

function ntp_snmp_collect_nrpe ()
{
printf "${Yellow} ===== Installaed NTP packages ====${NC}\n\n"
rpm -qa | grep ntp-
printf "${Yellow} ===== NTP service status ====${NC}\n\n"
systemctl status ntpd --no-pager;echo;printf "${Cyan} NTP service is `systemctl is-enabled ntpd`${NC}\n\n"
printf "${Yellow} ===== NTP servers ====${NC}\n\n"
grep server /etc/ntp.conf
printf "${Yellow} ===== Installaed Chrony packages ====${NC}\n\n"
rpm -qa | grep chrony
printf "${Yellow} ===== Chrony service status ====${NC}\n\n"
systemctl status chronyd --no-pager;echo;printf "${Cyan} Chrony service is `systemctl is-enabled chronyd`${NC}\n\n"
printf "${Yellow} ===== Chrony servers ====${NC}\n\n"
grep server /etc/chrony.conf
printf "${Yellow} ===== Installaed SNMP packages ====${NC}\n\n"
rpm -qa | grep net-snmp
printf "${Yellow} ===== SNMP service status ====${NC}\n\n"
systemctl status snmpd --no-pager;echo;printf "${Cyan} SNMP service is `systemctl is-enabled snmpd`${NC}\n\n"
printf "${Yellow} ===== Installaed collectd packages ====${NC}\n\n"
rpm -qa | grep collectd
printf "${Yellow}===== collectd ===${NC}\n\n"
systemctl status collectd --no-pager;printf "${Cyan} Collectd service is `systemctl is-enabled collectd`${NC}\n\n"; ls -lrt /opt/monitoring/graphite
printf "${Yellow}===== nrpe ===${NC}\n\n"
rpm -qa | grep nrpe
systemctl status nrpe --no-pager;printf "${Cyan} NRPE service is `systemctl is-enabled nrpe`${NC}\n\n"
}

function centrify ()
{
printf "${Yellow} ===== Installaed Centrify packages ====${NC}\n\n"
rpm -qa | grep -i centrify
printf "${Yellow}=== adinfo output===${NC}\n\n"
adinfo
printf "${Yellow}===== dainfo output ===${NC}\n\n"
dainfo
printf "${Yellow}===== Centrify service status====${NC}\n\n"
systemctl -a | grep centrify

}
function block_multipath_devices ()
{
printf "${Yellow}===== multipath devices ===${NC}\n\n"
multipath -ll | awk '/dm-/{ printf( "%d\n Disk #%d: %s ", a, ++c, $1"\t"$2); a=0;}; /^size/ {printf $1"\tactive_paths:"} /active ready running/{ a+=1 } END {print a}' | column -t
printf "${Yellow}===== udev devices ===${NC}\n\n"
ls -lrt /dev/oracle
printf "${Yellow}===== udev devices permission ===${NC}\n\n"
ls -lrt /dev/oracle | awk -F / 'NR>1 {print $NF}' | while read line; do ls -lrt /dev/$line;done
}
function kernel_limit ()
{
printf "${Yellow}===== kernel parameter ===${NC}\n\n"
cat /etc/sysctl.conf | grep -v ^# | grep -v ^$
printf "${Yellow}===== limit parameter ===${NC}\n\n"
cat /etc/security/limits.conf  | grep -v ^# | grep -v ^$
}
function users_timezone_kdump ()
{
printf "${Yellow}===== Users ===${NC}\n\n"
cat /etc/passwd | egrep 'bash|ksh'
printf "${Yellow}===== timezone ===${NC}\n\n"
ls -lrt /etc/localtime;date
printf "${Yellow}===== kdump ===${NC}\n\n"
systemctl status kdump --no-pager;printf "${Cyan} KDUMP service is `systemctl is-enabled kdump`${NC}\n\n"

}
function continue ()
{
printf "\n Enter to continue...";read;clear
}

clear
while true
do
        printf "%20s ${Yellow}1. FS and permission${NC} \n"
        printf "%20s ${Yellow}2. Network and route${NC} \n"
        printf "%20s ${Yellow}3. NTP,SNMP,collectd and nrpe configuration${NC} \n"
        printf "%20s ${Yellow}4. Centrify status${NC} \n"
		printf "%20s ${Yellow}5. multipath and udev devices${NC} \n"
		printf "%20s ${Yellow}6. Kernel parameter and limits${NC} \n"
		printf "%20s ${Yellow}7. users,timezone and kdump${NC} \n"
		printf "%20s ${Yellow}8. Exit${NC} \n"
        printf "\n%25s Enter your option:"
        read option
        case $option in
                1)      fs;continue
                ;;
                2)      network;continue
                ;;
                3)      ntp_snmp_collect_nrpe;continue
                ;;
                4)      centrify;continue
                ;;
				5)		block_multipath_devices;continue
				;;
				6)		kernel_limit;continue
				;;
				7)		users_timezone_kdump;continue
				;;
                *)
                        exit;
                ;;
        esac
done
